
package com.thanone.netmanager.service.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OhwgWebService", targetNamespace = "http://ws.service.netmanager.thanone.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OhwgWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "check", targetNamespace = "http://ws.service.netmanager.thanone.com/", className = "com.thanone.netmanager.service.ws.Check")
    @ResponseWrapper(localName = "checkResponse", targetNamespace = "http://ws.service.netmanager.thanone.com/", className = "com.thanone.netmanager.service.ws.CheckResponse")
    public String check(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "telAc", targetNamespace = "http://ws.service.netmanager.thanone.com/", className = "com.thanone.netmanager.service.ws.TelAc")
    @ResponseWrapper(localName = "telAcResponse", targetNamespace = "http://ws.service.netmanager.thanone.com/", className = "com.thanone.netmanager.service.ws.TelAcResponse")
    public String telAc(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

}
