
package com.thanone.netmanager.service.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OhwgWebServiceImplService", targetNamespace = "http://ws.service.netmanager.thanone.com/", wsdlLocation = "http://192.168.1.158:8080/netmanager/ohwg/User?wsdl")
public class OhwgWebServiceImplService
    extends Service
{

    private final static URL OHWGWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException OHWGWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName OHWGWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws.service.netmanager.thanone.com/", "OhwgWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.158:8080/netmanager/ohwg/User?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OHWGWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        OHWGWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public OhwgWebServiceImplService() {
        super(__getWsdlLocation(), OHWGWEBSERVICEIMPLSERVICE_QNAME);
    }

    public OhwgWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OHWGWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public OhwgWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, OHWGWEBSERVICEIMPLSERVICE_QNAME);
    }

    public OhwgWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OHWGWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public OhwgWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OhwgWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OhwgWebService
     */
    @WebEndpoint(name = "OhwgWebServiceImplPort")
    public OhwgWebService getOhwgWebServiceImplPort() {
        return super.getPort(new QName("http://ws.service.netmanager.thanone.com/", "OhwgWebServiceImplPort"), OhwgWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OhwgWebService
     */
    @WebEndpoint(name = "OhwgWebServiceImplPort")
    public OhwgWebService getOhwgWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.service.netmanager.thanone.com/", "OhwgWebServiceImplPort"), OhwgWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OHWGWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw OHWGWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return OHWGWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
